export const VERIFICATION_EMAIL_SENT = 'VERIFICATION_EMAIL_SENT';
export const VERIFY_FIRST = 'VERIFY_FIRST';
export const UNREGISTERD_USER = 'UNREGISTERD_USER';
export const INCOREECT_PASSWORD = 'INCOREECT_PASSWORD';
