export const EMAIL_EXIST = 'auth/email-already-in-use'
export const WEAK_PASSWORD = 'auth/weak-password'
export const USER_NOT_FOUND = 'auth/user-not-found'
export const INCORRECT_PASSWORD = 'auth/wrong-password'
export const REQUIRES_RECENT_LOGIN = 'auth/requires-recent-login'