export const GET_BLOGS_FROM_DB = 'GET_BLOGS_FROM_DB';
export const DISPLAY_BLOGS = 'DISPLAY_BLOGS';
export const GET_CATEGORIES_FROM_DB = 'GET_CATEGORIES_FROM_DB';
export const DISPLAY_CATEGORIES = 'DISPLAY_CATEGORIES';
export const SET_CURRENT_CATEGORY_ID = 'SET_CURRENT_CATEGORY_ID';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';