export const GET_BLOGS_FROM_DB = 'GET_BLOGS_FROM_DB';
export const DISPLAY_BLOGS = 'DISPLAY_BLOGS';
export const GET_CATEGORIES_FROM_DB = 'GET_CATEGORIES_FROM_DB';
export const DISPLAY_CATEGORIES = 'DISPLAY_CATEGORIES';